// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PruebaDualTech.Data;

#nullable disable

namespace PruebaDualTech.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250323195838_CorregirOrden")]
    partial class CorregirOrden
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PruebaDualTech.Entities.Cliente", b =>
                {
                    b.Property<long>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ClienteId"));

                    b.Property<long>("Identidad")
                        .HasColumnType("bigint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClienteId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("PruebaDualTech.Entities.DetalleOrden", b =>
                {
                    b.Property<long>("DetalleOrdenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DetalleOrdenId"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal>("Impuesto")
                        .HasColumnType("decimal(10,4)");

                    b.Property<long>("OrdenId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProductoId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,4)");

                    b.HasKey("DetalleOrdenId");

                    b.HasIndex("OrdenId");

                    b.HasIndex("ProductoId");

                    b.ToTable("DetallesOrden");
                });

            modelBuilder.Entity("PruebaDualTech.Entities.Orden", b =>
                {
                    b.Property<long>("OrdenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OrdenId"));

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Impuesto")
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,4)");

                    b.HasKey("OrdenId");

                    b.ToTable("Ordenes");
                });

            modelBuilder.Entity("PruebaDualTech.Entities.Producto", b =>
                {
                    b.Property<long>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProductoId"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Existencia")
                        .HasColumnType("bigint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,4)");

                    b.HasKey("ProductoId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("PruebaDualTech.Entities.DetalleOrden", b =>
                {
                    b.HasOne("PruebaDualTech.Entities.Orden", "Orden")
                        .WithMany("DetallesOrden")
                        .HasForeignKey("OrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PruebaDualTech.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orden");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("PruebaDualTech.Entities.Orden", b =>
                {
                    b.Navigation("DetallesOrden");
                });
#pragma warning restore 612, 618
        }
    }
}
